artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  handler: allandclive/chicken-disease-1
  local_data_file: artifacts/data_ingestion/Train
  csv_file: artifacts/data_ingestion/train_data.csv